### ISSUE TITLE
Disputa abierta con @pepemb

### ISSUE THREAD

**Issue by caperucitaferoz** [devalls/repository#3]
https://github.com/devalls/repository/blob/e3e35ddfa2dc005a153eb97f08855ee549ee824a/repository.devalls/addon.xml#L45

Por favor, puedes eliminar el repositorio de pepemebe, tengo abierta una disputa con el: 
https://github.com/pepemebe/mag/issues/1

Gracias

**Comment by devalls** [comment]
Por supuesto. ~~Esta misma tarde lo elimino.~~ Eliminado.

Saludos.

**Comment by caperucitaferoz** [comment]
Muchas gracias
